name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@latest
        with:
          java-version: '20'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run tests
        run: mvn test

      - name: Generate Allure reports
        run: |
          allure generate --clean